import { library } from '@fortawesome/fontawesome-svg-core';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faCartArrowDown,
  faDroplet,
  faEnvelope,
  faExternalLink,
  faHandshake,
  faHeart,
  faLock,
  faPen,
  faPlus,
  faRightFromBracket,
  faSeedling,
  faSort,
  faSortDown,
  faSortUp,
  faSun,
  faTemperatureHalf,
  faTruckFast,
  faUser,
  faXmark
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faAngleDown,
  faAngleUp,
  faAngleLeft,
  faAngleRight,
  faCartArrowDown,
  faDroplet,
  faEnvelope,
  faHandshake,
  faHeart,
  faLock,
  faPen,
  faPlus,
  faRightFromBracket,
  faXmark,
  faExternalLink,
  faGithub,
  faSeedling,
  faSort,
  faSortUp,
  faSortDown,
  faSun,
  faTemperatureHalf,
  faTruckFast,
  faUser,
  faExternalLink
);
export const faIconsList = library.definitions;
