default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'developer') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'password') %>

development:
  <<: *default
  database: plant_shop_dev

test:
  <<: *default
  database: plant_shop_test

production:
  <<: *default
  database: plant_shop_production
  username: api
